# This workflow will build a Java project with Gradle and push a new docker image to Quay.io
name: Build and Push Image to Quay.io

on:
  push:
    branches: [ main ]

env:
  APP_NAME: vulnerableapp
  APP_FOLDER: VulnerableApp 
  IMAGE_NAMESPACE: mboira_sysdig
  IMAGE_REGISTRY: quay.io
  CLUSTER_NAMESPACE: default
  

jobs:
  login-build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Checkout new changes
        uses: actions/checkout@v2
        with:
          java-version: 1.8
      -
        name: Grant execute permission for gradlew
        working-directory: ./VulnerableApp
        run: chmod +x gradlew
      -
        name: Build with Gradle and Push
        working-directory: VulnerableApp
        run: ./gradlew jib

      - 
        name: OpenShift login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          # openshift_username:
          # openshift_password:
          insecure_skip_tls_verify: true
          namespace: ${{ env.IMAGE_NAMESPACE }}

      - name: Create and expose app
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ env.APP_NAME }}
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.APP_NAME }}:latest
          namespace: ${{ env.CLUSTER_NAMESPACE }}
