# This workflow will build a Java project with Gradle and push a new docker image to Quay.io
name: Build and Push Image to Quay.io

on:
  push:
    branches: [ main ]

env:
  APP_FOLDER: VulnerableApp

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Checkout new changes
        uses: actions/checkout@v2
        with:
          java-version: 1.8
      -
        name: Grant execute permission for gradlew
        working-directory: ./VulnerableApp
        run: chmod +x gradlew
      -
        name: Build with Gradle and Push
        working-directory: VulnerableApp
        run: ./gradlew jib
